config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#homepage"
  resources :meals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id         :bigint           not null, primary key
#  name       :string
#  image_url  :string
#  recipe_url :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Meal < ApplicationRecord
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:edit, :update, :destroy]

  def index
    @meals = Meal.all
  end

  def new
  end

  def create
    if @meal = Meal.create(meal_params)
      flash[:success] = "#{@meal.name} saved"
    else
      flash[:error] = "oopsie woopsie"
    end

    redirect_to meals_path
  end

  def edit
  end

  def update
    if @meal.update(meal_params)
      flash[:success] = "#{@meal.name} updated"
    else
      flash[:error] = "oopsie woopsie"
    end

    redirect_to meals_path
  end

  def destroy
    if @meal.destroy
      flash[:success] = "#{@meal.name} deleted"
    else
      flash[:error] = "oopsie woopsie"
    end

    redirect_to meals_path
  end

  private

  def meal_params
    params.require(:meal).permit(
      :name,
      :recipe_url,
      :image_url
    )
  end

  def set_meal
    @meal = Meal.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def homepage
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipme2023</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meals/_form.html.haml
= simple_form_for @meal || Meal.new do |f|
  = f.input :name
  = f.input :recipe_url, as: :string
  = f.input :image_url, as: :string

  = f.submit

app/views/meals/edit.html.haml
%h2
  Edit
  = @meal.name

= render 'form'

app/views/meals/index.html.haml
%h2 Allan and Christin's Cool Meal Ideas

= link_to 'new', new_meal_path

- @meals.each do |meal|
  %p= meal.name
  %p= meal.recipe_url
  %p= meal.image_url
  = link_to 'Edit', edit_meal_path(meal)
  = link_to 'Delete', meal_path(meal), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }
  %hr

app/views/meals/new.html.haml
%h2 Create new meal

= render 'form'

app/views/static_pages/homepage.html.haml
%h1 RecipMe

= link_to 'Meals', meals_path